// Regenerates src/pricing-snapshot.ts from the official price list.
//
//   npm run pricing:snapshot                 always rewrite, show the diff
//   npm run pricing:snapshot -- --auto       what the weekly workflow runs:
//       write only when a price changed or a model was added, and refuse
//       (exit 1, nothing written) when a price moved implausibly far
//
// It uses the same parser and checks as `vantage pricing update`, so the
// bundled prices are never typed by hand. Models the page no longer lists
// stay in the list, so old sessions keep their prices.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { fetchPriceTable, diffPrices, formatChange, hasDrift, implausibleChanges, nextSnapshot } from "../src/pricing-source.ts";
import { SNAPSHOT } from "../src/pricing-snapshot.ts";
import type { PriceTable } from "../src/pricing.ts";

const target = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "src", "pricing-snapshot.ts");

function renderSnapshot(t: PriceTable): string {
  const rows = Object.entries(t.models).map(([id, m]) => {
    const fields = `input: ${m.input}, cache_write_5m: ${m.cache_write_5m}, cache_write_1h: ${m.cache_write_1h}, cache_read: ${m.cache_read}, output: ${m.output}`;
    return `    ${JSON.stringify(id)}: { name: ${JSON.stringify(m.name)}, ${fields} },`;
  });
  return (
    `// GENERATED by \`npm run pricing:snapshot\` from the official price list — do\n` +
    `// not edit by hand (see scripts/pricing-snapshot.ts and src/pricing.ts).\n\n` +
    `import type { PriceTable } from "./pricing.ts";\n\n` +
    `export const SNAPSHOT: PriceTable = {\n` +
    `  source: ${JSON.stringify(t.source)},\n` +
    `  fetchedAt: ${JSON.stringify(t.fetchedAt)},\n` +
    `  models: {\n${rows.join("\n")}\n  },\n};\n`
  );
}

const auto = process.argv.includes("--auto");
const fetched = await fetchPriceTable();
for (const s of fetched.skipped) process.stderr.write(`skipped ${s}\n`);

const d = diffPrices(SNAPSHOT.models, fetched.models);
for (const id of d.added) process.stdout.write(`+ ${id}\n`);
for (const c of d.changed) process.stdout.write(`~ ${formatChange(c)}\n`);
for (const id of d.unlisted) process.stdout.write(`- ${id} (no longer listed, kept)\n`);

if (auto && !hasDrift(d)) {
  process.stdout.write("no price changes\n");
  process.exit(0);
}
const suspicious = auto ? implausibleChanges(d) : [];
if (suspicious.length) {
  process.stderr.write(`refusing to update: these prices moved more than 10x, which needs a person to confirm:\n`);
  for (const line of suspicious) process.stderr.write(`  ${line}\n`);
  process.exit(1);
}

const { skipped: _skipped, ...table } = fetched;
const next = nextSnapshot(SNAPSHOT, table);
fs.writeFileSync(target, renderSnapshot(next));
process.stdout.write(`wrote ${path.relative(process.cwd(), target)} · ${Object.keys(next.models).length} models\n`);
