// Regenerates src/pricing-snapshot.ts from the official price list.
//
//   npm run pricing:snapshot
//
// Run it when the weekly "Pricing drift" workflow fails, review the diff it
// prints, and commit the regenerated file. It uses the same parser and checks
// as `vantage pricing update`, so the bundled prices are never typed by hand.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { fetchPriceTable, diffPrices, formatChange } from "../src/pricing-source.ts";
import { SNAPSHOT } from "../src/pricing-snapshot.ts";
import type { PriceTable } from "../src/pricing.ts";

const target = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "src", "pricing-snapshot.ts");

function renderSnapshot(t: PriceTable): string {
  const rows = Object.entries(t.models).map(([id, m]) => {
    const fields = `input: ${m.input}, cache_write_5m: ${m.cache_write_5m}, cache_write_1h: ${m.cache_write_1h}, cache_read: ${m.cache_read}, output: ${m.output}`;
    return `    ${JSON.stringify(id)}: { name: ${JSON.stringify(m.name)}, ${fields} },`;
  });
  return (
    `// GENERATED by \`npm run pricing:snapshot\` from the official price list — do\n` +
    `// not edit by hand (see scripts/pricing-snapshot.ts and src/pricing.ts).\n\n` +
    `import type { PriceTable } from "./pricing.ts";\n\n` +
    `export const SNAPSHOT: PriceTable = {\n` +
    `  source: ${JSON.stringify(t.source)},\n` +
    `  fetchedAt: ${JSON.stringify(t.fetchedAt)},\n` +
    `  models: {\n${rows.join("\n")}\n  },\n};\n`
  );
}

const fetched = await fetchPriceTable();
for (const s of fetched.skipped) process.stderr.write(`skipped ${s}\n`);

const d = diffPrices(SNAPSHOT.models, fetched.models);
for (const id of d.added) process.stdout.write(`+ ${id}\n`);
for (const c of d.changed) process.stdout.write(`~ ${formatChange(c)}\n`);
for (const id of d.unlisted) process.stdout.write(`- ${id} (no longer listed)\n`);

const { skipped: _skipped, ...table } = fetched;
fs.writeFileSync(target, renderSnapshot(table));
process.stdout.write(`wrote ${path.relative(process.cwd(), target)} · ${Object.keys(table.models).length} models\n`);
