// Regenerates src/pricing-snapshot.ts from the official price lists
// (Anthropic, OpenAI, Google).
//
//   npm run pricing:snapshot                 always rewrite, show the diff
//   npm run pricing:snapshot -- --auto       what the weekly workflow runs:
//       write only when a price changed or a model was added, and refuse
//       (exit 1, nothing written) when a page does not parse or a price
//       moved implausibly far
//   npm run pricing:snapshot -- openai       only the providers named
//   npm run pricing:snapshot -- --page openai=saved.md
//       read a provider's page from a saved copy instead of fetching it
//       (for networks that cannot reach it); dated by the file's mtime
//
// It uses the same parsers and checks as `vantage pricing update`, so the
// bundled prices are never typed by hand. Models a page no longer lists
// stay in the list, so old sessions keep their prices.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  fetchProviderTable,
  parseProviderPage,
  pricingSourceUrl,
  diffPrices,
  formatChange,
  hasDrift,
  implausibleChanges,
  nextSnapshot,
} from "../src/pricing-source.ts";
import { SNAPSHOTS } from "../src/pricing-snapshot.ts";
import { PRICE_PROVIDERS, type BasePrices, type PriceProvider, type PriceTable } from "../src/pricing.ts";

const target = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "src", "pricing-snapshot.ts");

const base = (p: BasePrices): string =>
  `input: ${p.input}, cache_write_5m: ${p.cache_write_5m}, cache_write_1h: ${p.cache_write_1h}, cache_read: ${p.cache_read}, output: ${p.output}`;

function renderTable(provider: PriceProvider, t: PriceTable): string {
  const rows = Object.entries(t.models).map(([id, m]) => {
    let fields = base(m);
    if (m.long) fields += `, long: { above: ${m.long.above}, ${base(m.long)} }`;
    if (m.next) fields += `, next: { from: ${JSON.stringify(m.next.from)}, ${base(m.next)} }`;
    return `      ${JSON.stringify(id)}: { name: ${JSON.stringify(m.name)}, ${fields} },`;
  });
  return (
    `  ${provider}: {\n` +
    `    provider: ${JSON.stringify(provider)},\n` +
    `    source: ${JSON.stringify(t.source)},\n` +
    `    fetchedAt: ${JSON.stringify(t.fetchedAt)},\n` +
    `    models: {\n${rows.join("\n")}\n    },\n  },\n`
  );
}

function renderSnapshot(tables: Record<PriceProvider, PriceTable>): string {
  return (
    `// GENERATED by \`npm run pricing:snapshot\` from the official price lists —\n` +
    `// do not edit by hand (see scripts/pricing-snapshot.ts and src/pricing.ts).\n\n` +
    `import type { PriceProvider, PriceTable } from "./pricing.ts";\n\n` +
    `export const SNAPSHOTS: Record<PriceProvider, PriceTable> = {\n` +
    PRICE_PROVIDERS.map((p) => renderTable(p, tables[p])).join("") +
    `};\n\n` +
    `export const SNAPSHOT: PriceTable = SNAPSHOTS.anthropic;\n`
  );
}

const argv = process.argv.slice(2);
const auto = argv.includes("--auto");
const pages = new Map<string, string>();
const named: PriceProvider[] = [];
const isProvider = (x: string): x is PriceProvider => (PRICE_PROVIDERS as string[]).includes(x);
for (let i = 0; i < argv.length; i++) {
  const arg = argv[i]!;
  if (arg === "--auto") continue;
  if (arg === "--page") {
    const [provider, file] = (argv[++i] ?? "").split("=");
    if (!provider || !file || !isProvider(provider)) {
      process.stderr.write(`--page takes <${PRICE_PROVIDERS.join("|")}>=<file>\n`);
      process.exit(2);
    }
    pages.set(provider, file);
    if (!named.includes(provider)) named.push(provider);
  } else if (isProvider(arg)) {
    if (!named.includes(arg)) named.push(arg);
  } else {
    process.stderr.write(`unknown argument "${arg}"\n`);
    process.exit(2);
  }
}

const next = { ...SNAPSHOTS };
let drift = false;
const suspicious: string[] = [];
for (const provider of named.length ? named : PRICE_PROVIDERS) {
  let fetched;
  try {
    const page = pages.get(provider);
    if (page) {
      const at = fs.statSync(page).mtime;
      const { models, skipped } = parseProviderPage(provider, fs.readFileSync(page, "utf8"), at);
      fetched = { provider, source: pricingSourceUrl(provider), fetchedAt: at.toISOString(), models, skipped };
    } else {
      fetched = await fetchProviderTable(provider);
    }
  } catch (err) {
    process.stderr.write(`${provider}: ${(err as Error).message} — nothing written\n`);
    process.exit(1);
  }
  process.stdout.write(`${provider}: ${Object.keys(fetched.models).length} models\n`);
  for (const s of fetched.skipped) process.stderr.write(`  skipped ${s}\n`);
  const current = SNAPSHOTS[provider];
  const d = diffPrices(current.models, fetched.models);
  for (const id of d.added) process.stdout.write(`+ ${id}\n`);
  for (const c of d.changed) process.stdout.write(`~ ${formatChange(c)}\n`);
  for (const id of d.unlisted) process.stdout.write(`- ${id} (no longer listed, kept)\n`);
  drift ||= hasDrift(d);
  suspicious.push(...implausibleChanges(d));
  const { skipped: _skipped, ...table } = fetched;
  next[provider] = nextSnapshot(current, { ...table, provider });
}

if (auto && !drift) {
  process.stdout.write("no price changes\n");
  process.exit(0);
}
if (auto && suspicious.length) {
  process.stderr.write(`refusing to update: these prices moved more than 10x, which needs a person to confirm:\n`);
  for (const line of suspicious) process.stderr.write(`  ${line}\n`);
  process.exit(1);
}

fs.writeFileSync(target, renderSnapshot(next));
const total = PRICE_PROVIDERS.reduce((n, p) => n + Object.keys(next[p].models).length, 0);
process.stdout.write(`wrote ${path.relative(process.cwd(), target)} · ${total} models\n`);
