// GENERATED by `npm run pricing:snapshot` from the official price list — do
// not edit by hand (see scripts/pricing-snapshot.ts and src/pricing.ts).

import type { PriceTable } from "./pricing.ts";

export const SNAPSHOT: PriceTable = {
  source: "https://platform.claude.com/docs/en/about-claude/pricing.md",
  fetchedAt: "2026-09-23T09:53:50.491Z",
  models: {
    "claude-fable-5-1": { name: "Claude Fable 5.1", input: 10, cache_write_5m: 12.5, cache_write_1h: 20, cache_read: 0.25, output: 50 },
    "claude-mythos-5-1": { name: "Claude Mythos 5.1", input: 10, cache_write_5m: 12.5, cache_write_1h: 20, cache_read: 0.25, output: 50 },
    "claude-fable-5": { name: "Claude Fable 5", input: 10, cache_write_5m: 12.5, cache_write_1h: 20, cache_read: 1, output: 50 },
    "claude-mythos-5": { name: "Claude Mythos 5", input: 10, cache_write_5m: 12.5, cache_write_1h: 20, cache_read: 1, output: 50 },
    "claude-opus-5-5": { name: "Claude Opus 5.5", input: 4, cache_write_5m: 5, cache_write_1h: 8, cache_read: 0.2, output: 20 },
    "claude-opus-5": { name: "Claude Opus 5", input: 5, cache_write_5m: 6.25, cache_write_1h: 10, cache_read: 0.5, output: 25 },
    "claude-opus-4-8": { name: "Claude Opus 4.8", input: 5, cache_write_5m: 6.25, cache_write_1h: 10, cache_read: 0.5, output: 25 },
    "claude-opus-4-7": { name: "Claude Opus 4.7", input: 5, cache_write_5m: 6.25, cache_write_1h: 10, cache_read: 0.5, output: 25 },
    "claude-opus-4-6": { name: "Claude Opus 4.6", input: 5, cache_write_5m: 6.25, cache_write_1h: 10, cache_read: 0.5, output: 25 },
    "claude-opus-4-5": { name: "Claude Opus 4.5", input: 5, cache_write_5m: 6.25, cache_write_1h: 10, cache_read: 0.5, output: 25 },
    "claude-opus-4-1": { name: "Claude Opus 4.1", input: 15, cache_write_5m: 18.75, cache_write_1h: 30, cache_read: 1.5, output: 75 },
    "claude-opus-4": { name: "Claude Opus 4", input: 15, cache_write_5m: 18.75, cache_write_1h: 30, cache_read: 1.5, output: 75 },
    "claude-sonnet-5": { name: "Claude Sonnet 5", input: 2, cache_write_5m: 2.5, cache_write_1h: 4, cache_read: 0.2, output: 10 },
    "claude-sonnet-4-6": { name: "Claude Sonnet 4.6", input: 3, cache_write_5m: 3.75, cache_write_1h: 6, cache_read: 0.3, output: 15 },
    "claude-sonnet-4-5": { name: "Claude Sonnet 4.5", input: 3, cache_write_5m: 3.75, cache_write_1h: 6, cache_read: 0.3, output: 15 },
    "claude-sonnet-4": { name: "Claude Sonnet 4", input: 3, cache_write_5m: 3.75, cache_write_1h: 6, cache_read: 0.3, output: 15 },
    "claude-haiku-4-5": { name: "Claude Haiku 4.5", input: 1, cache_write_5m: 1.25, cache_write_1h: 2, cache_read: 0.1, output: 5 },
    "claude-3-5-haiku": { name: "Claude Haiku 3.5", input: 0.8, cache_write_5m: 1, cache_write_1h: 1.6, cache_read: 0.08, output: 4 },
  },
};
